# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: python:buster
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install python requirements
          command: cd lang/python && pip3 install -r requirements.txt -t `pwd`
      - run:
          name: Run tests
          command: cd lang/python && python3 -m unittest
  deploy:
    docker:
      - image: python:buster
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install python requirements
          command: cd lang/python && pip3 install -r requirements.txt -t `pwd`
      - run:
          name: Deploy Code
          command: printf "Dummy deployment to $ENV_NAME"
workflows:
  version: 2.1
  build_test:
    jobs:
      - build:
          context: dev
          filters:
            tags:
              only: /.*/
            branches:
              only: /(^master)|(^dev)/
      - deploy:
          context: dev
          requires:
            - build
          filters:
            tags:
              only: /(^v\d+.*)/
            branches:
              only: /(^master)|(^dev)/
      - deploy:
          context: prod
          requires:
            - build
          filters:
            tags:
              only: /(^v\d+.*)/
            branches:
              ignore: /.*/
